import { Kysely, sql } from "kysely";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function down(db: Kysely<any>): Promise<void> {
    await sql`ALTER TABLE "app"."contacts"
            ALTER COLUMN "contact_id"
            DROP IDENTITY IF EXISTS
            `.execute(db)
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function up(db: Kysely<any>): Promise<void> {
    // contacts.contact_id
    await sql`ALTER TABLE "app"."contacts"
            ALTER COLUMN "contact_id"
            ADD GENERATED BY DEFAULT AS IDENTITY
            `.execute(db)

    await sql`SELECT setval(
                pg_get_serial_sequence('"app"."contacts"', 'contact_id'),
                COALESCE((SELECT MAX("contact_id") FROM "app"."contacts"), 1)
            )
            `.execute(db)

    // document_type.type_of_doc_id
    await sql`ALTER TABLE "app"."document_type"
            ALTER COLUMN "type_of_doc_id"
            ADD GENERATED BY DEFAULT AS IDENTITY
            `.execute(db)

    await sql`SELECT setval(
                pg_get_serial_sequence('"app"."document_type"', 'type_of_doc_id'),
                COALESCE((SELECT MAX("type_of_doc_id") FROM "app"."document_type"), 1)
            )
            `.execute(db)

    // org_category.org_category_id
    await sql`ALTER TABLE "app"."org_category"
            ALTER COLUMN "org_category_id"
            ADD GENERATED BY DEFAULT AS IDENTITY
            `.execute(db)

    await sql`SELECT setval(
                pg_get_serial_sequence('"app"."org_category"', 'org_category_id'),
                COALESCE((SELECT MAX("org_category_id") FROM "app"."org_category"), 1)
            )
            `.execute(db)

    // org_type.org_type_id
    await sql`ALTER TABLE "app"."org_type"
            ALTER COLUMN "org_type_id"
            ADD GENERATED BY DEFAULT AS IDENTITY
            `.execute(db)

    await sql`SELECT setval(
                pg_get_serial_sequence('"app"."org_type"', 'org_type_id'),
                COALESCE((SELECT MAX("org_type_id") FROM "app"."org_type"), 1)
            )
            `.execute(db)

    // organisations.organisation_id
    await sql`ALTER TABLE "app"."organisations"
            ALTER COLUMN "organisation_id"
            ADD GENERATED BY DEFAULT AS IDENTITY
            `.execute(db)

    await sql`SELECT setval(
                pg_get_serial_sequence('"app"."organisations"', 'organisation_id'),
                COALESCE((SELECT MAX("organisation_id") FROM "app"."organisations"), 1)
            )
            `.execute(db)
}
