name: compass-beta

services:
  db:
    image: postgres:18.6
    restart: always
    environment:
      POSTGRES_USER: compass
      POSTGRES_DB: compass
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-passwd
    volumes:
      - db-data:/var/lib/postgresql
    secrets:
      - postgres-passwd
  web:
    image: dhsc-compass-beta
    ports:
      - "3001:3001"
    secrets:
      - postgres-passwd
    volumes:
      - app-src-views:/compass/views

volumes:
  db-data:
  app-src-views:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./views

secrets:
  postgres-passwd:
    file: ./postgres-passwd
