const allTrusts = [
  "Airedale NHS Foundation Trust",
  "Ashford and St Peter's Hospitals NHS Foundation Trust",
  "Avon and Wiltshire Mental Health Partnership NHS Trust",
  "Barking, Havering and Redbridge University Hospitals NHS Trust",
  "Barnsley Hospital NHS Foundation Trust",
  "Barts Health NHS Trust",
  "Bedfordshire Hospitals NHS Foundation Trust",
  "Berkshire Healthcare NHS Foundation Trust",
  "Birmingham and Solihull Mental Health NHS Foundation Trust",
  "Birmingham Community Healthcare NHS Foundation Trust",
  "Birmingham Women's and Children's NHS Foundation Trust",
  "Blackpool Teaching Hospitals NHS Foundation Trust",
  "Bolton NHS Foundation Trust",
  "Bradford District Care NHS Foundation Trust",
  "Bradford Teaching Hospitals NHS Foundation Trust",
  "Buckinghamshire Healthcare NHS Trust",
  "Calderdale and Huddersfield NHS Foundation Trust",
  "Cambridge University Hospitals NHS Foundation Trust",
  "Cambridgeshire and Peterborough NHS Foundation Trust",
  "Cambridgeshire Community Services NHS Trust",
  "Central and North West London NHS Foundation Trust",
  "Central London Community Healthcare NHS Trust",
  "Chelsea and Westminster Hospital NHS Foundation Trust",
  "Cheshire and Wirral Partnership NHS Foundation Trust",
  "Chesterfield Royal Hospital NHS Foundation Trust",
  "Clatterbridge Cancer Centre NHS Foundation Trust",
  "Cornwall Partnership NHS Foundation Trust",
  "County Durham and Darlington NHS Foundation Trust",
  "Coventry and Warwickshire Partnership NHS Trust",
  "Croydon Health Services NHS Trust",
  "Dartford and Gravesham NHS Trust",
  "Derbyshire Healthcare NHS Foundation Trust",
  "Devon Partnership NHS Trust",
  "Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust",
  "Dorset County Hospital NHS Foundation Trust",
  "Dorset HealthCare University NHS Foundation Trust",
  "Dudley Group NHS Foundation Trust",
  "East and North Hertfordshire Teaching NHS Trust",
  "East Cheshire NHS Trust",
  "East Kent Hospitals University NHS Foundation Trust",
  "East Lancashire Hospitals NHS Trust",
  "East London NHS Foundation Trust",
  "East Midlands Ambulance Service NHS Trust",
  "East of England Ambulance Service NHS Trust",
  "East Suffolk and North Essex NHS Foundation Trust",
  "East Sussex Healthcare NHS Trust",
  "Epsom and St Helier University Hospitals NHS Trust",
  "Essex Partnership University NHS Foundation Trust",
  "Frimley Health NHS Foundation Trust",
  "Gateshead Health NHS Foundation Trust",
  "George Eliot Hospital NHS Trust",
  "Gloucestershire Health and Care NHS Foundation Trust",
  "Gloucestershire Hospitals NHS Foundation Trust",
  "Great Ormond Street Hospital for Children NHS Foundation Trust",
  "Great Western Hospitals NHS Foundation Trust",
  "Guy's and St Thomas' NHS Foundation Trust",
  "Hampshire Hospitals NHS Foundation Trust",
  "Harrogate and District NHS Foundation Trust",
  "Hertfordshire Community NHS Trust",
  "Hertfordshire Partnership University NHS Foundation Trust",
  "Hounslow and Richmond Community Healthcare NHS Trust",
  "Hull University Teaching Hospitals NHS Trust",
  "Humber Teaching NHS Foundation Trust",
  "Imperial College Healthcare NHS Trust",
  "Isle of Wight NHS Trust",
  "Kent Community Health NHS Foundation Trust",
  "Kettering General Hospital NHS Foundation Trust",
  "King's College Hospital NHS Foundation Trust",
  "Kingston Hospital NHS Foundation Trust",
  "Lancashire Teaching Hospitals NHS Foundation Trust",
  "Lancashire and South Cumbria NHS Foundation Trust",
  "Leeds and York Partnership NHS Foundation Trust",
  "Leeds Community Healthcare NHS Trust",
  "Leeds Teaching Hospitals NHS Trust",
  "Leicestershire Partnership NHS Trust",
  "Lewisham and Greenwich NHS Trust",
  "Lincolnshire Partnership NHS Foundation Trust",
  "Liverpool Community Health NHS Trust",
  "Liverpool Heart and Chest Hospital NHS Foundation Trust",
  "Liverpool University Hospitals NHS Foundation Trust",
  "Liverpool Women's NHS Foundation Trust",
  "London Ambulance Service NHS Trust",
  "London North West University Healthcare NHS Trust",
  "Maidstone and Tunbridge Wells NHS Trust",
  "Manchester University NHS Foundation Trust",
  "Medway NHS Foundation Trust",
  "Mersey and West Lancashire Teaching Hospitals NHS Trust",
  "Mersey Care NHS Foundation Trust",
  "Mid and South Essex NHS Foundation Trust",
  "Mid Cheshire Hospitals NHS Foundation Trust",
  "Milton Keynes University Hospital NHS Foundation Trust",
  "Moorfields Eye Hospital NHS Foundation Trust",
  "Newcastle upon Tyne Hospitals NHS Foundation Trust",
  "Norfolk and Norwich University Hospitals NHS Foundation Trust",
  "Norfolk and Suffolk NHS Foundation Trust",
  "Norfolk Community Health and Care NHS Trust",
  "North Bristol NHS Trust",
  "North Cumbria Integrated Care NHS Foundation Trust",
  "North East Ambulance Service NHS Foundation Trust",
  "North East London NHS Foundation Trust",
  "North Staffordshire Combined Healthcare NHS Trust",
  "North Tees and Hartlepool NHS Foundation Trust",
  "North West Ambulance Service NHS Trust",
  "North West Anglia NHS Foundation Trust",
  "North West Boroughs Healthcare NHS Foundation Trust",
  "Northamptonshire Healthcare NHS Foundation Trust",
  "Northern Lincolnshire and Goole Hospitals NHS Foundation Trust",
  "Northumbria Healthcare NHS Foundation Trust",
  "Nottingham University Hospitals NHS Trust",
  "Nottinghamshire Healthcare NHS Foundation Trust",
  "Oxford Health NHS Foundation Trust",
  "Oxford University Hospitals NHS Foundation Trust",
  "Oxleas NHS Foundation Trust",
  "Pennine Care NHS Foundation Trust",
  "Queen Victoria Hospital NHS Foundation Trust",
  "Rotherham Doncaster and South Humber NHS Foundation Trust",
  "Rotherham NHS Foundation Trust",
  "Royal Berkshire NHS Foundation Trust",
  "Royal Devon University Healthcare NHS Foundation Trust",
  "Royal Free London NHS Foundation Trust",
  "Royal United Hospitals Bath NHS Foundation Trust",
  "Salisbury NHS Foundation Trust",
  "Sandwell and West Birmingham Hospitals NHS Trust",
  "Sheffield Children's NHS Foundation Trust",
  "Sheffield Health Partnership University NHS Foundation Trust",
  "Sheffield Teaching Hospitals NHS Foundation Trust",
  "Sherwood Forest Hospitals NHS Foundation Trust",
  "Shrewsbury and Telford Hospital NHS Trust",
  "Shropshire Community Health NHS Trust",
  "Solent NHS Trust",
  "Somerset NHS Foundation Trust",
  "South Central Ambulance Service NHS Foundation Trust",
  "South East Coast Ambulance Service NHS Foundation Trust",
  "South London and Maudsley NHS Foundation Trust",
  "South Staffordshire and Shropshire Healthcare NHS Foundation Trust",
  "South Tees Hospitals NHS Foundation Trust",
  "South Tyneside and Sunderland NHS Foundation Trust",
  "South West London and St George's Mental Health NHS Trust",
  "South West Yorkshire Partnership NHS Foundation Trust",
  "Southern Health NHS Foundation Trust",
  "St George's University Hospitals NHS Foundation Trust",
  "Stockport NHS Foundation Trust",
  "Surrey and Borders Partnership NHS Foundation Trust",
  "Surrey and Sussex Healthcare NHS Trust",
  "Tees, Esk and Wear Valleys NHS Foundation Trust",
  "Torbay and South Devon NHS Foundation Trust",
  "University College London Hospitals NHS Foundation Trust",
  "University Hospitals Coventry and Warwickshire NHS Trust",
  "University Hospitals Birmingham NHS Foundation Trust",
  "University Hospitals Bristol and Weston NHS Foundation Trust",
  "University Hospitals Dorset NHS Foundation Trust",
  "University Hospitals of Derby and Burton NHS Foundation Trust",
  "University Hospitals of Morecambe Bay NHS Foundation Trust",
  "University Hospitals of North Midlands NHS Trust",
  "University Hospitals Plymouth NHS Trust",
  "University Hospital Southampton NHS Foundation Trust",
  "University Hospitals Sussex NHS Foundation Trust",
  "Walsall Healthcare NHS Trust",
  "Walton Centre NHS Foundation Trust",
  "West Hertfordshire Teaching Hospitals NHS Trust",
  "West Suffolk NHS Foundation Trust",
  "The Whittington Hospital NHS Trust",
  "Wirral University Teaching Hospital NHS Foundation Trust",
  "Worcestershire Acute Hospitals NHS Trust",
  "Wrightington, Wigan and Leigh NHS Foundation Trust",
  "Wye Valley NHS Trust",
  "York and Scarborough Teaching Hospitals NHS Foundation Trust",
  "Yorkshire Ambulance Service NHS Trust",
  "2gether NHS Foundation Trust",
  "North West Boroughs Healthcare NHS Foundation Trust",
  "Cambridge University Hospitals NHS Foundation Trust",
  "Aintree University Hospitals NHS Foundation Trust",
  "Worcestershire Acute Hospitals NHS Trust",
  "Barnet, Enfield and Haringey Mental Health NHS Trust",
  "Barts Health NHS Trust",
  "Basildon and Thurrock University Hospitals NHS Foundation Trust",
  "Hampshire Hospitals NHS Foundation Trust",
  "Avon and Wiltshire Mental Health Partnership NHS Trust",
  "Bedfordshire Hospitals NHS Foundation Trust",
  "East of England Ambulance Service NHS Trust",
  "South Essex Partnership University NHS Foundation Trust",
  "Heart of England NHS Foundation Trust",
  "Birmingham Community Healthcare NHS Trust",
  "Birmingham Women's NHS Foundation Trust",
  "East Lancashire Hospitals NHS Trust",
  "Blackpool Teaching Hospitals NHS Foundation Trust",
  "Bradford District Care NHS Foundation Trust",
  "Brighton and Sussex University Hospitals NHS Trust",
  "Brighton and Sussex University Hospitals NHS Trust",
  "Royal Liverpool and Broadgreen University Hospitals NHS Trust",
  "South London Healthcare NHS Trust",
  "Buckinghamshire Healthcare NHS Trust",
  "East Lancashire Hospitals NHS Trust",
  "Burton Hospitals NHS Foundation Trust",
  "Pennine Acute Hospitals NHS Trust",
  "Calderstones Partnership NHS Foundation Trust",
  "Camden and Islington NHS Foundation Trust",
  "Liverpool Heart and Chest Hospital NHS Foundation Trust",
  "Carlisle Hospitals",
  "Central Manchester University Hospitals NHS Foundation Trust",
  "Chase Farm Hospitals",
  "Chesterfield Royal Hospital NHS Foundation Trust",
  "Sandwell and West Birmingham Hospitals NHS Trust",
  "City Hospitals Sunderland NHS Foundation Trust",
  "Colchester Hospital University NHS Foundation Trust",
  "Surrey and Sussex Healthcare NHS Trust",
  "North West Ambulance Service NHS Trust",
  "Cumbria Partnership NHS Foundation Trust",
  "East Midlands Ambulance Service NHS Trust",
  "Derbyshire Healthcare NHS Foundation Trust",
  "Rotherham Doncaster and South Humber NHS Foundation Trust",
  "South Western Ambulance Service NHS Trust",
  "Dudley Integrated Health and Care NHS Trust",
  "North East Ambulance Service NHS Trust",
  "East of England Ambulance Service NHS Trust",
  "Gloucestershire Hospitals NHS Foundation Trust",
  "East London NHS Foundation Trust",
  "Yeovil District Hospital NHS Foundation Trust",
  "Surrey and Sussex Healthcare NHS Trust",
  "East Sussex Healthcare NHS Trust",
  "Epsom and St Helier University Hospitals NHS Trust",
  "East of England Ambulance Service NHS Trust",
  "Colchester Hospital University NHS Foundation Trust",
  "Newcastle upon Tyne Hospitals NHS Foundation Trust",
  "Glenfield Hospital",
  "Great Western Ambulance Service NHS Trust",
  "Gloucestershire Care Services NHS Trust",
  "2gether NHS Foundation Trust",
  "Gloucestershire Hospitals NHS Foundation Trust",
  "Good Hope Hospital",
  "Grantham and District Hospital",
  "South Western Ambulance Service",
  "North West Ambulance Service",
  "Guy's and St Thomas' NHS Foundation Trust",
  "Hammersmith Hospitals",
  "South Central Ambulance Service NHS Trust",
  "Southern Health NHS Foundation Trust",
  "Royal Brompton and Harefield NHS Foundation Trust",
  "Central and North West London NHS Foundation Trust",
  "Heart of England NHS Foundation Trust",
  "Heatherwood and Wexham Park Hospitals NHS Foundation Trust",
  "Horton General Hospital",
  "South East Coast Ambulance Service NHS Trust",
  "Maidstone and Tunbridge Wells NHS Trust",
  "Worcestershire Acute Hospitals NHS Trust",
  "Queen Elizabeth Hospital King's Lynn NHS Trust",
  "North West Ambulance Service NHS Trust",
  "Lancashire and South Cumbria NHS Foundation Trust",
  "Leeds and York Partnership NHS Foundation Trust",
  "Leeds and York Partnership NHS Foundation Trust",
  "University Hospitals of Leicester NHS Trust",
  "University Hospitals of Leicester NHS Trust",
  "East Midlands Ambulance Service NHS Trust",
  "East Midlands Ambulance Service NHS Trust",
  "Bedfordshire Hospitals NHS Foundation Trust",
  "Manchester Mental Health and Social Care Trust",
  "Croydon Health Services NHS Trust",
  "Medway Community Healthcare",
  "North West Ambulance Service NHS Trust",
  "Mid Essex Hospital Services NHS Trust",
  "Maidstone and Tunbridge Wells NHS Trust",
  "Mid Staffordshire NHS Foundation Trust",
  "Brighton and Sussex University Hospitals NHS Trust",
  "NHS Direct",
  "North Cumbria University Hospitals NHS Trust",
  "North Cumbria University Hospitals NHS Trust",
  "North Essex Partnership University NHS Foundation Trust",
  "Pennine Acute Hospitals NHS Trust",
  "North West London Hospitals NHS Trust",
  "Northern Devon Healthcare NHS Trust",
  "Sheffield Teaching Hospitals NHS Foundation Trust",
  "North East Ambulance Service NHS Trust",
  "Nottingham University Hospitals NHS Trust",
  "East Midlands Ambulance Service NHS Trust",
  "Pennine Acute Hospitals NHS Trust",
  "South Central Ambulance Service NHS Trust",
  "Oxford Health NHS Foundation Trust",
  "Southern Health NHS Foundation Trust",
  "Pennine Acute Hospitals NHS Trust",
  "Peterborough and Stamford Hospitals NHS Foundation Trust",
  "Peterborough and Stamford Hospitals NHS Foundation Trust",
  "University Hospitals Plymouth NHS Trust",
  "South London Healthcare NHS Trust",
  "Nottingham University Hospitals NHS Trust",
  "South London Healthcare NHS Trust",
  "Pennine Acute Hospitals NHS Trust",
  "Northamptonshire Healthcare NHS Foundation Trust",
  "South Central Ambulance Service NHS Trust",
  "Royal Cornwall Hospitals NHS Trust",
  "Royal London Hospital",
  "Royal Liverpool and Broadgreen University Hospitals NHS Trust",
  "Royal Liverpool and Broadgreen University Hospitals NHS Trust",
  "Royal London Hospital",
  "Royal National Throat, Nose and Ear Hospital",
  "Royal Victoria Infirmary",
  "Western Sussex Hospitals NHS Foundation Trust",
  "Salford Royal NHS Foundation Trust",
  "Sandwell and West Birmingham Hospitals NHS Trust",
  "Gloucestershire Hospitals NHS Foundation Trust",
  "Sheffield Health Partnership University NHS Foundation Trust",
  "Somerset Partnership NHS Foundation Trust",
  "South Essex Partnership University NHS Foundation Trust",
  "South London Healthcare NHS Trust",
  "University Hospital of South Manchester NHS Foundation Trust",
  "South Staffordshire and Shropshire Healthcare NHS Foundation Trust",
  "South Tyneside NHS Foundation Trust",
  "South West Yorkshire Mental Health NHS Trust",
  "South Yorkshire Metropolitan Ambulance and Paramedic Service NHS Trust",
  "Southend University Hospital NHS Foundation Trust",
  "University Hospital Southampton NHS Foundation Trust",
  "North Bristol NHS Trust",
  "Southport and Ormskirk Hospital NHS Trust",
  "Southport and Ormskirk Hospital NHS Trust",
  "St George's University Hospitals NHS Foundation Trust",
  "St Helens and Knowsley Teaching Hospitals NHS Trust",
  "Epsom and St Helier University Hospitals NHS Trust",
  "Leeds Teaching Hospitals NHS Trust",
  "Imperial College Healthcare NHS Trust",
  "Guy's and St Thomas' NHS Foundation Trust",
  "Staffordshire Ambulance Service",
  "Norfolk and Suffolk NHS Foundation Trust",
  "Sussex Ambulance Service",
  "Great Western Hospitals NHS Foundation Trust",
  "Taunton and Somerset NHS Foundation Trust",
  "Teddington Memorial Hospital",
  "Yorkshire Ambulance Service",
  "Torbay and Southern Devon Health and Care NHS Trust",
  "Trafford Healthcare NHS Trust",
  "South Central Ambulance Service",
  "Leeds Teaching Hospitals NHS Trust",
  "Aintree University Hospitals NHS Foundation Trust",
  "University Hospital of South Manchester NHS Foundation Trust",
  "University Hospitals Bristol and Weston NHS Foundation Trust",
  "Wakefield and Pontefract Community Health NHS Trust",
  "Warrington Hospital",
  "Dorset County Hospital NHS Foundation Trust",
  "West London NHS Trust",
  "West Middlesex University Hospital NHS Trust",
  "West Yorkshire Metropolitan Ambulance Service",
  "South Western Ambulance Service",
  "Western Sussex Hospitals NHS Foundation Trust",
  "Weston Area Health NHS Trust",
  "Weston Park Hospital",
  "Western Sussex Hospitals NHS Foundation Trust",
  "Wrightington, Wigan and Leigh NHS Foundation Trust",
  "Yeovil District Hospital NHS Foundation Trust"
]

module.exports = allTrusts
