name: Alpha CI on pull requests

on:
  pull_request:
    paths:
      - 'src/alpha-prototype/**'

jobs:
  tests:
    name: Javascript tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/alpha-prototype
    strategy:
      matrix:
        node: ['20', '22']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run javascript tests
        run: npm run test:ci
